- id: format-go
  name: Format Go code and sort imports
  entry: pre-commit-hooks format-go
  language: golang
  additional_dependencies: [ 'github.com/daixiang0/gci@v0.11.2', 'mvdan.cc/gofumpt@v0.5.0' ]
  types: [ 'go' ]
- id: go-mod-tidy
  name: go mod tidy
  entry: go mod tidy
  language: system
  pass_filenames: false
